version: '3.8'
services:
  gamification-db:
    image: mysql:8.0.21
    container_name: gamification-db
    restart: always
    ports:
      - '3307:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=gamification_engine_db

  gamification-api:
    image: ghcr.io/rockandstones/gamification-api:latest
    container_name: gamification-api
    ports:
      - '8081:8080'
    environment:
      MYSQL_HOST: gamification-db
      MYSQL_PORT: 3307
      MYSQL_USER: root
      MYSQL_PASSWORD: mysql
    depends_on:
      - gamification-db
    command: bash -c "/usr/wait-for-it.sh --timeout=0 gamification-db:3306 && java -Djava.security.egd=file:/dev/./urandom -jar /app/gamification-api.jar"

  stoneoverflow-db:
    image: mysql:8.0.21
    container_name: stoneoverflow-db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=stoneoverflow-db
    volumes:
      - ./images/stoneoverflow-db/init/:/docker-entrypoint-initdb.d/

  stoneoverflow-webapp:
    image: ghcr.io/rockandstones/stoneoverflow:latest
    container_name: stoneoverflow-webapp
    ports:
      - "8080:8080"
      - "9443:9443"
    volumes:
      - ../src/main/liberty/config/server.env:/config/server.env
    depends_on:
      - stoneoverflow-db
      - gamification-api
