version: '3'
services:
  sql:
    image: mysql:8.0.21
    container_name: stoneoverflow_db
    restart: always
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=mysql
      - MYSQL_DATABASE=db_stoneoverflow
    volumes:
      - ./images/sqlServer/init/:/docker-entrypoint-initdb.d/

  webapp:
     image: ghcr.io/rockandstones/stoneoverflow:latest
     container_name: stoneoverflow
     ports:
       - "8080:8080"
       - "9443:9443"
     volumes:
       - ../src/main/liberty/config/server.env:/config/server.env
     depends_on:
       - sql
