name: MVN & E2E Tests
on:
  push:
    branches:
      - '*'
      - '!master'
  pull_request:
    branches: [ dev ]

jobs:
  test:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
      - name: Setup JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11

      - uses: actions/checkout@v2

      - uses: actions/cache@v1
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: NPM install
        run: cd e2e && npm ci && cd ..

      - name: Build with maven
        run: mvn clean package

      - name: Start servers
        run: |
          mvn liberty:create liberty:install-feature liberty:deploy
          mvn liberty:start
          docker-compose up -d mysql

      - name: Run maven tests
        run: |
          mvn verify

      - name: Run e2e tests
        run: |
          cd e2e
          npx codeceptjs run --override '{"helpers": {"Puppeteer": {"show": false}}}' --steps
          cd ..

      - name: Stop servers
        run: |
          mvn liberty:stop
          docker-compose down
